### ISSUE TITLE
Customer feature request: NserviceBus performance counters collectors to work with Prometheus

### ISSUE THREAD

**Issue by seanfarmar** [Particular/NServiceBus.Metrics.PerformanceCounters#2]
> I am doing a POC using Service Fabric in house as container to run my NserviceBus Endpoints we are using sql transport all looks good so far.
> 
> The issue is we are using Prometheus for our systems monitoring ( I have wired it in to the pipeline) what I would like to do is refactor NserviceBus performance counters collectors to work with Prometheus and turn off NserviceBus performance counters so I do not have to provision every node with NserviceBus performance counters.
> 
> Can you help?

**Comment by dvdstelt** [comment]
Currently in `ReceiveStatisticsFeature` we do `context.Pipeline.Remove("ReceivePerformanceDiagnosticsBehavior");` on SetUp. This disables the performance counters that are enabled by default.
Then we use `context.Pipeline.OnReceivePipelineCompleted` to see what's going on. But that's in a version of NServiceBus that's not officially out yet :-)

**Comment by dvdstelt** [comment]
I don't know who the original author of the question was. But since we now have `NServiceBus.Metrics` it would seem you'd be able to have a custom report, like we do in this repository. So instead of refactoring this repo/package, you can easily use them. You can look at this repo for example how to do that though. You can see here how to create this custom report : https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/NServiceBus.Metrics.PerformanceCounters/PerformanceCountersFeature.cs#L34-L38
