### ISSUE TITLE
CriticalTime and ProcessingTime don't get reset

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.Metrics.PerformanceCounters#38]
## Problem
CriticalTime and ProcessingTime performance counters don't get reset when no messages are being processed. 

## Root cause
The metrics resetting logic was part of `NServiceBus.Metrics` until 1.1.0 release when it was removed.

## Solution
Introduce resetting logic to `NServiceBus.Metrics.PerformanceCounters`.

**Comment by Scooletz** [comment]
I started working on these and I have some problems with grasping it. Which part should be responsible for resetting it? PerformanceCounters or the Metrics package? The following code updates the perf counters values:

```
var timers = rootObject["Timers"]?.ToObject<List<Timer>>() ?? new List<Timer>();
foreach (var timer in timers)
{
  var performanceCounterInstance = cache.Get(new CounterInstanceName(timer.Name, context));
  performanceCounterInstance.RawValue = timer.Histogram.LastValue / 1000;
}
```

It takes all the timers, which currently are `Processing Time` and `Critical Time` and reports the values.
If these values should be reported as zero, maybe, at first place, they should be Reset in metrics package? If not, why should it be only in **this** reporter? Do we want to provide a custom report to other users' functions that has bad data in it?

I'd like you to chime in @Particular/metrics-maintainers

**Comment by tmasternak** [comment]
I like the current situation when `NSB.Metrics` does not hold any auto reset magic. Otherwise it would make the public contract quite weird IMO.

I would suggest to add explicit ifs for `Critical Time` and `Processing Time` and for those track the last time value was non-zero an on that basis add zeroing logic that we previously had.

**Comment by dvdstelt** [comment]
> I like the current situation when NSB.Metrics does not hold any auto reset magic.

Exactly. When it was in Core it was tightly together. With 1.0 release it was forgotten, 1.0.1 it was added back in. Unfortunately, it was removed again by accident. But unfortunately, with the Metrics.NET there was no way of telling in `NSB.Metrics.PerfCounters` when the last message had come in. So we _had to put it in `NSB.Metrics`_. Now we can tell in the new package because of the probes and the fact that those aren't averaged out. This is a very specific PerfCounter issue, also because in NSB3 the incorrect counters were selected. The newly defined counter-type doesn't need this, PerfMon will fix it. But with these 'old' counters we specifically need to reset them.

**Comment by Scooletz** [comment]
Ok. The two opinions above make it clear, that it should be perfcounter based reset.
