### ISSUE TITLE
Exception calling "GetCounters" with "0" argument(s): "Counter is not single instance, an instance name needs to be specified."

### ISSUE THREAD

**Issue by VladimirMakaev** [Particular/NServiceBus.Metrics.PerformanceCounters#9]
When we're running the script created by MSBuild task we're getting the exception:
```
Exception calling "GetCounters" with "0" argument(s): "Counter is not single instance, an
instance name needs to be specified."
At line:1 char:1
+ $existingCounters = ([System.Diagnostics.PerformanceCounterCategory]: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```
The thing is the script actually works first time but it stops later on if you recreate a PowerShell process and run again.

**Comment by mikeminutillo** [comment]
It looks like we create the perf counter category as a [multi-instance](https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/ScriptBuilder/PowerShellCounterWriter.cs#L72) category which means we [can't query it](https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/ScriptBuilder/PowerShellCounterWriter.cs#L49) without specifying an instance.

We're getting the [`ArgumentException` listed here](https://msdn.microsoft.com/en-us/library/ew6c05xw(v=vs.110).aspx). We need to call [this version](https://msdn.microsoft.com/en-us/library/wsdb1s67(v=vs.110).aspx) and pass in an instance name.

The [C# version](https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/ScriptBuilder/CSharpCounterWriter.cs) of the script will have the same issue.

It works the first time because the category doesn't exist so we don't query it for a list of existing counters. Once we create the category, subsequent runs cause us to run the offending code.

**Comment by VladimirMakaev** [comment]
@mikeminutillo Thanks for your response.
That's pretty much what we've figured out too. The script was never intended to work. I guess we need to hard code the counter instance name as Endpoint name in the copy of the script for now as it's the way you use it here. 
https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/blob/develop/src/NServiceBus.Metrics.PerformanceCounters/PerformanceCountersFeature.cs

Do you have an ETA for the proper fix as it's going to be painful to automate multiple endpoint deployment as we'd have to maintain those ps1 scripts with different names hardcoded in them?

**Comment by mikeminutillo** [comment]
@VladimirMakaev the simplest fix is to always drop and recreate the counters. This will make the scripts significantly simpler. I have created a PR for it https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/pull/10

Once it's been reviewed, we can merge and release it.

**Comment by mikeminutillo** [comment]
@VladimirMakaev this change has been reviewed and merged. I will go into the next release of this component.
